# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import main.media_path
import phonenumber_field.modelfields
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=main.media_path.company_path, verbose_name='Логотип')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Ярлык')),
                ('street_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('short_info', models.TextField(blank=True, max_length=250, null=True, verbose_name='Краткая информация')),
                ('info', redactor.fields.RedactorField(verbose_name='Подробная информация')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. адрес')),
                ('legal_data', models.TextField(blank=True, max_length=500, null=True, verbose_name='Юридистические данные')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда редактирован')),
                ('status', models.CharField(choices=[('MD', 'На модерации'), ('AC', 'Активный'), ('DC', 'Отклоненный'), ('IN', 'Неактивный')], default='MD', max_length=2, verbose_name='Статус')),
                ('categories', models.ManyToManyField(related_name='categories', to='webapp.Category', verbose_name='Категории')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем редактирован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Учреждения',
                'verbose_name': 'Учреждение',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
