# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import main.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=main.media_path.company_path, verbose_name='Логотип'),
        ),
    ]
