# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Номер телефона')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='webapp.Company', verbose_name='Учреждение')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
    ]
