# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import main.media_path
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_companycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main.media_path.specialist_path, verbose_name='Фото')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Ярлык')),
                ('street_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес')),
                ('short_info', models.TextField(blank=True, max_length=250, null=True, verbose_name='Краткая информация')),
                ('info', redactor.fields.RedactorField(verbose_name='Подробная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда редактирован')),
                ('categories', models.ManyToManyField(related_name='specialist_categories', to='webapp.Category', verbose_name='Категории')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_specialists', to='webapp.Company', verbose_name='Учреждение')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем редактирован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_specialists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
