# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:24
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('webapp', '0007_specialistcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Услуги'),
        ),
    ]
