# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:00
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('webapp', '0008_specialist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Услуги'),
        ),
    ]
