# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20170905_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='message_decline',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Сообщение для отказа в регистрции'),
        ),
    ]
