# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0011_company_message_decline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_date', models.DateField(auto_now_add=True, verbose_name='Даты отправки инвайта')),
                ('accepted', models.BooleanField(default=False)),
                ('code', models.CharField(default=uuid.uuid4, editable=False, max_length=64)),
                ('invite_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Company', verbose_name='Приглашение в компанию')),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL, verbose_name='Приглашение от  отправителя')),
                ('invite_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL, verbose_name='Приглашение в отправителю')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
    ]
