# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '------'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
