# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_specialist_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='message_decline',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Сообщение для отказа в регистрции'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='status',
            field=models.CharField(choices=[('MD', 'На модерации'), ('AC', 'Активный'), ('DC', 'Отклоненный'), ('IN', 'Неактивный')], default='MD', max_length=2, verbose_name='Статус'),
        ),
    ]
