# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20171003_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_certifications', to='webapp.Specialist'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='webapp.Company', verbose_name='Учреждение'),
        ),
    ]
