# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20171003_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник')),
                ('tuesday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вторник')),
                ('wednesday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Среда')),
                ('thursday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Четверг')),
                ('friday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пятница')),
                ('saturday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Суббота')),
                ('sunday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Воскресенье')),
                ('lunch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Обед')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_setting_specialist', to='webapp.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name_plural': 'Настройка расписаний',
                'verbose_name': 'Настройка расписание',
            },
        ),
    ]
