# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0015_auto_20171003_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Диапазон')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_company', to='webapp.Company', verbose_name='Учреждение')),
            ],
            options={
                'verbose_name_plural': 'Рейтинги (Отзывы)',
                'verbose_name': 'Рейтинг',
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='rating',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='rating',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_specialist', to='webapp.Specialist', verbose_name='Специалист'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
