# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20171024_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Рейтинг'),
        ),
    ]
