# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20171028_1612'),
        ('webapp', '0017_company_rating'),
    ]

    operations = [
    ]
