# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0020_favoritespecialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Когда редактирован'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем редактирован'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтвержден'), ('armored', 'Отказано'), ('armored', 'Бронирован')], default='armored', max_length=10, verbose_name='Статус'),
        ),
    ]
