# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20171104_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время')),
                ('interval', models.CharField(blank=True, max_length=255, null=True, verbose_name='Интервал')),
                ('live_recording', models.CharField(blank=True, max_length=255, null=True, verbose_name='Живая запись')),
            ],
            options={
                'verbose_name_plural': 'Рабочие дни',
                'verbose_name': 'Рабочий день',
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтвержден'), ('refused', 'Отказано'), ('armored', 'Бронирован')], default='armored', max_length=10, verbose_name='Статус'),
        ),
    ]
