# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_remove_schedulesetting_time_interval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeInterval',
        ),
    ]
