# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_delete_timeinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='lunch_settings',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fridays', to='webapp.WorkDay', verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='webapp.WorkDay', verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mondays', to='webapp.WorkDay', verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturdays', to='webapp.WorkDay', verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sundays', to='webapp.WorkDay', verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='webapp.WorkDay', verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesdays', to='webapp.WorkDay', verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='schedulesetting',
            name='wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesdays', to='webapp.WorkDay', verbose_name='Среда'),
        ),
    ]
