# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_remove_schedulesetting_lunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesetting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_setting_company', to='webapp.Company'),
        ),
    ]
