# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(related_name='companies', to='webapp.Employees', verbose_name='Пользователь'),
        ),
    ]
