# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20171116_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='company',
        ),
        migrations.AddField(
            model_name='specialist',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_specialists', to='webapp.Company', verbose_name='Учреждение'),
        ),
    ]
