# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20171127_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='company_specialists', to='webapp.Company', verbose_name='Учреждение'),
        ),
    ]
