# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 11:33
from __future__ import unicode_literals

from django.db import migrations
import main.media_path
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20171129_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=main.media_path.category_icon_upload_path, verbose_name='Иконка для моб приложение'),
        ),
    ]
