# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги (Отзывы)'},
        ),
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2018-01-12', verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
