# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import main.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20180117_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='mobile_photo',
            field=models.ImageField(default='', upload_to=main.media_path.specialist_mobile_path, verbose_name='Фото для мобильного приложение'),
            preserve_default=False,
        ),
    ]
