# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import main.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_specialist_mobile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to=main.media_path.mobile_company_path, verbose_name='Логотип для телефонов'),
        ),
    ]
