# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_company_mobile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_phone',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Короткий номер'),
        ),
    ]
