# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 06:07
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_company_short_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='info',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='Подробная информация'),
        ),
    ]
