# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20180302_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Эл. адрес'),
        ),
    ]
