# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_auto_20180319_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='legal_data',
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. адрес'),
        ),
    ]
