# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_auto_20180321_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesetting',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто?'),
        ),
    ]
