# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_schedulesetting_hidden'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schedulesetting',
            managers=[
                ('public_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='specialist',
            name='status',
            field=models.CharField(choices=[('MD', 'На модерации'), ('AC', 'Активный'), ('DC', 'Отклоненный'), ('IN', 'Неактивный')], default='AC', max_length=2, verbose_name='Статус'),
        ),
    ]
