# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_auto_20180323_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='status',
            field=models.CharField(choices=[('MD', 'На модерации'), ('AC', 'Активный'), ('DC', 'Отклоненный'), ('IN', 'Неактивный')], default='MD', max_length=2, verbose_name='Статус'),
        ),
    ]
