# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
