# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import main.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_auto_20180328_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.media_path.specialist_path, verbose_name='Фото'),
        ),
    ]
